# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160113_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Anonymous')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Anonymous')], default=0),
        ),
    ]
